name: "Echidna"

description: "Run echidna-test"

inputs:
  files:
    description: "Solidity files to analyze"
    required: true
  contract:
    description: "Contract to analyze"
    required: false
  config:
    description: "Config file (CLI arguments override config options)"
    required: false
  format:
    description: "Output format: json, text, none. Disables interactive UI"
    required: false
  corpus-dir:
    description: "Directory to store corpus and coverage data"
    required: false
  check-asserts:
    description: "Check asserts in the code"
    required: false
  multi-abi:
    description: "Use multi-abi mode of testing"
    required: false
  test-limit:
    description: "Number of sequences of transactions to generate during testing"
    required: false
  shrink-limit:
    description: "Number of tries to attempt to shrink a failing sequence of transactions"
    required: false
  seq-len:
    description: "Number of transactions to generate during testing"
    required: false
  contract-addr:
    description: "Address to deploy the contract to test"
    required: false
  deployer:
    description: "Address of the deployer of the contract to test"
    required: false
  sender:
    description: "Addresses to use for the transactions sent during testing"
    required: false
  seed:
    description: "Run with a specific seed"
    required: false
  crytic-args:
    description: "Additional arguments to use in crytic-compile for the compilation of the contract to test"
    required: false
  solc-args:
    description: "Additional arguments to use in solc for the compilation of the contract to test"
    required: false
  solc-version:
    description: "Version of the Solidity compiler to use"
    required: false
  negate-exit-status:
    description: "Apply logical NOT to echidna-test's exit status (for testing the action)"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
