name: echidna

author: JP Smith

version: 1.0.0.0

ghc-options: -Wall -fno-warn-orphans -O2 -threaded +RTS -N -RTS

dependencies:
  - aeson                >= 1.3    && < 1.5
  - base
  - ansi-terminal
  - brick
  - bytestring           >= 0.10.8 && < 0.11
  - containers           >= 0.5.7  && < 0.6
  - data-dword           >= 0.3.1  && < 0.4
  - data-has
  - deepseq
  - directory            >= 1.3    && < 1.4
  - exceptions           >= 0.8.1  && < 0.11
  - hashable
  - hevm
  - lens                 >= 4.15.1 && < 4.17
  - lens-aeson
  - MonadRandom
  - mtl                  >= 2.2.1  && < 2.3
  - optparse-applicative >= 0.13.0 && < 0.15
  - process              >= 1.4.3  && < 1.7
  - stm
  - temporary            >= 1.2.1  && < 1.4
  - text                 >= 1.2.2  && < 1.3
  - transformers
  - unliftio
  - unliftio-core
  - vector               >= 0.11.0 && < 0.13
  - vty
  - wl-pprint-annotated
  - unix
  - word8
  - yaml
  - unordered-containers
  - random

default-extensions:
  - OverloadedStrings

library:
  source-dirs: lib/

executables:
  echidna-test:
    main: Main.hs
    source-dirs: src/
    dependencies: echidna
    when:
        - condition: os(linux)
          ghc-options:
            - -threaded
            - -static
            - -O2
          cc-options: -static
          ld-options: -static -pthread

tests:
  echidna-testsuite:
    main: Spec.hs
    source-dirs: src/test
    dependencies:
      - echidna
      - tasty
      - tasty-hunit
