name: echidna

author: Trail of Bits <echidna-dev@trailofbits.com>
maintainer: Trail of Bits <echidna-dev@trailofbits.com>

version: 2.0.2

ghc-options: -Wall -fno-warn-orphans -O2 -threaded +RTS -N -RTS

dependencies:
  - base
  - aeson
  - ansi-terminal
  - base16-bytestring
  - binary
  - brick
  - base16-bytestring
  - bytestring
  - containers
  - data-dword
  - data-has
  - deepseq
  - extra
  - directory
  - exceptions
  - filepath
  - hashable
  - hevm
  - html-entities
  - lens
  - lens-aeson
  - ListLike
  - megaparsec
  - MonadRandom
  - mtl
  - optparse-applicative
  - process
  - random
  - rosezipper
  - semver
  - sbv
  - stm
  - split
  - temporary
  - text
  - transformers
  - time
  - unix
  - unliftio
  - unliftio-core
  - utf8-string
  - unordered-containers
  - vector
  - vector-instances
  - vty
  - wl-pprint-annotated
  - word8
  - yaml

default-extensions:
  - OverloadedStrings

library:
  source-dirs: lib/

executables:
  echidna-test:
    main: Main.hs
    source-dirs: src/
    dependencies: echidna
    when:
        - condition: os(linux) && flag(static)
          ghc-options:
            - -static
            - -O2
          cc-options: -static
          ld-options: -static -pthread
        - condition: os(linux)
          ghc-options:
            - -O2
          ld-options: -pthread

tests:
  echidna-testsuite:
    main: Spec.hs
    source-dirs: src/test
    dependencies:
      - echidna
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    when:
        - condition: os(linux) && flag(static)
          ghc-options:
            - -static
            - -O2
          cc-options: -static
          ld-options: -static -pthread
        - condition: os(linux)
          ghc-options:
            - -O2
          ld-options: -pthread

flags:
  static:
    description: Pass -static to ghc when linking the stack binary.
    manual: true
    default: true
