name: echidna

author: Trail of Bits <echidna-dev@trailofbits.com>
maintainer: Trail of Bits <echidna-dev@trailofbits.com>

version: 2.1.1

# https://github.com/haskell/cabal/issues/4739
ghc-options: -Wall -fno-warn-orphans -O2 -threaded +RTS -N -RTS -optP-Wno-nonportable-include-path

dependencies:
  - base
  - aeson
  - base16-bytestring
  - binary
  - bytestring
  - code-page
  - containers
  - data-bword
  - data-dword
  - deepseq
  - extra
  - directory
  - exceptions
  - filepath
  - hashable
  - hevm
  - html-entities
  - lens
  - ListLike
  - MonadRandom
  - mtl
  - optparse-applicative
  - process
  - random
  - rosezipper
  - semver
  - split
  - text
  - transformers
  - time
  - unliftio
  - utf8-string
  - vector
  - with-utf8
  - word-wrap
  - yaml
  - http-conduit
  - html-conduit
  - xml-conduit
  - wreq

language: GHC2021

default-extensions:
  - DuplicateRecordFields
  - LambdaCase
  - MultiWayIf
  - NoFieldSelectors
  - OverloadedRecordDot
  - OverloadedStrings

library:
  source-dirs: lib/

when:
  - condition: "!os(windows)"
    cpp-options: -DINTERACTIVE_UI
    dependencies:
      - brick
      - unix
      - vty

executables:
  echidna:
    main: Main.hs
    source-dirs: src/
    dependencies: echidna
    when:
        - condition: (os(linux) || os(windows)) && flag(static)
          ghc-options:
            - -optl-static
        - condition: os(linux) || os(windows)
          ghc-options:
            - -O2
            - -optl-pthread
        - condition: os(darwin)
          extra-libraries: c++
          ld-options: -Wl,-keep_dwarf_unwind
        - condition: os(windows)
          extra-libraries: stdc++

tests:
  echidna-testsuite:
    main: Spec.hs
    source-dirs: src/test
    dependencies:
      - echidna
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    when:
        - condition: (os(linux) || os(windows)) && flag(static)
          ghc-options:
            - -optl-static
        - condition: os(linux) || os(windows)
          ghc-options:
            - -O2
            - -optl-pthread
        - condition: os(darwin)
          extra-libraries: c++
          ld-options: -Wl,-keep_dwarf_unwind
        - condition: os(windows)
          extra-libraries: stdc++

flags:
  static:
    description: Pass -static to ghc when linking the stack binary.
    manual: true
    default: false
