resolver: lts-12.18

packages:
- '.'

extra-deps:
- ghci-pretty-0.0.2
- hevm-0.21
- HSH-2.1.3
- ipprint-0.6
- multiset-0.3.4.1
- readline-1.0.3.0
- restless-git-0.7
- rosezipper-0.2
- s-cargot-0.1.4.0
- sr-extra-1.46.3.2
- text-format-0.3.2
- tree-view-0.5
- Unixutils-1.54.1
- hex-0.1.2

extra-include-dirs:
- /usr/local/opt/readline/include

extra-lib-dirs:
- /usr/local/opt/readline/lib
