resolver: lts-8.15

packages:
- '.'

extra-deps:
- git: https://github.com/dapphub/hevm.git
  commit: a2bda354fde1a8c1d990b95e468d60794106fa0d
- git: https://github.com/dapphub/libethjet-haskell
  commit: a1f13e95ec7619ebac60497c15b7f86449bf1d2a
- brick-0.18
- config-ini-0.2.1.1
- data-clist-0.1.2.0
- ghci-pretty-0.0.2
- hedgehog-0.6
- HSH-2.1.3
- ipprint-0.6
- megaparsec-6.4.0
- optparse-applicative-0.13.2.0
- parser-combinators-0.4.0
- restless-git-0.5.0
- rosezipper-0.2
- sr-extra-1.46.3.2
- temporary-1.2.1.1
- tree-view-0.5
- vty-5.16
- word-wrap-0.4.1
- s-cargot-0.1.4.0

extra-include-dirs:
- libethjet
extra-lib-dirs:
- libethjet
