resolver: lts-16.11

packages:
- '.'

extra-deps:
- git: https://github.com/dapphub/dapptools.git
  commit: 150dddc67b6cbad75fd4ae5a689452892f55ea26
  subdirs:
  - src/hevm

- ghci-pretty-0.0.2
- HSH-2.1.3
- monoidal-containers-0.6.0.1
- restless-git-0.7
- s-cargot-0.1.4.0
- text-format-0.3.2
- these-1.0.1
- tree-view-0.5
- witherable-0.3.5
- witherable-class-0
- github: dmjio/semver-range
  commit: d8d9db892ddb6ae267c9bcbc4f6602668433f12a
- github: leventerkok/sbv # 8.7.5
  # TODO: sbv 8.8
  commit: 91637c043d206530bc64d7eac88d2f80e8db0b85

extra-include-dirs:
- /usr/local/opt/readline/include

extra-lib-dirs:
- /usr/local/opt/readline/lib
