resolver: lts-14.27

packages:
- '.'

extra-deps:
- git: https://github.com/dapphub/dapptools.git
  commit: af84e2ee0a0654fdaa91186384233cf1731ee7ce
  subdirs:
  - src/hevm

- brick-0.46
- ghci-pretty-0.0.2
- multiset-0.3.4.1
- restless-git-0.7
- rosezipper-0.2
- s-cargot-0.1.4.0
- text-format-0.3.2
- tree-view-0.5
- HSH-2.1.3
- ipprint-0.6
- sr-extra-1.46.3.2
- Unixutils-1.54.1
- witherable-0.3.5
- witherable-class-0
- github: dmjio/semver-range
  commit: d8d9db892ddb6ae267c9bcbc4f6602668433f12a

extra-include-dirs:
- /usr/local/opt/readline/include

extra-lib-dirs:
- /usr/local/opt/readline/lib
