resolver: lts-10.0

packages:
- '.'

extra-deps:
- ./dapptools/src/hevm
- ./dapptools/src/libethjet-haskell
- brick-0.18
- config-ini-0.2.1.1
- data-clist-0.1.2.0
- ghci-pretty-0.0.2
- hedgehog-0.6
- HSH-2.1.3
- ipprint-0.6
- megaparsec-6.4.0
- parser-combinators-0.4.0
- restless-git-0.5.0
- rosezipper-0.2
- sr-extra-1.46.3.2
- temporary-1.2.1.1
- tree-view-0.5
- vty-5.16
- word-wrap-0.4.1
- s-cargot-0.1.4.0
- Unixutils-1.54.1
- optparse-applicative-0.14.2.0
- process-1.6.4.0
- readline-1.0.3.0
- time-1.6.0.1

nix:
  enable: true
  shell-file: dapptools.nix
  add-gc-roots: true
